From ubuntu:18.04

RUN apt-get update && apt-get -y install apt-utils locales gettext less wget nano 

# Set up the locale. 
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN groupadd -g 1000 arcgis && useradd -m -r arcgis -g arcgis -u 1000
ENV HOME /home/arcgis

WORKDIR ${HOME}
