
version: '2.1'
networks:
    cluster2:
        driver: bridge

services:
    pg-0:
        image: postdock/postgres:latest-postgres11-repmgr40
        environment:
            NODE_ID: 1 # Integer number of node (not required if can be extracted from NODE_NAME var, e.g. node-45 => 1045)
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pg-0
            
            PARTNER_NODES: "pg-0,pg-1"
            REPLICATION_PRIMARY_HOST: pg-0 # That should be ignored on the same node
            
            NODE_PRIORITY: 100  # (default: 100)
            SSH_ENABLE: 1
            #database we want to use for application
            POSTGRES_PASSWORD: 111222
            POSTGRES_USER: kalend
            POSTGRES_DB: kalend
            CLEAN_OVER_REWIND: 0
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "listen_addresses:'*';max_replication_slots:5;max_connections:4096"
                                  # in format variable1:value1[,variable2:value2[,...]] if CONFIGS_DELIMITER_SYMBOL=, and CONFIGS_ASSIGNMENT_SYMBOL=:
                                  # used for pgpool.conf file
            #defaults:
            CLUSTER_NAME: pg_cluster # default is pg_cluster
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: replication_password # default is replication_pass
            
        ports:
            - 5422:5432
        networks:
            cluster2:
        volumes:
            - /data/a/pg0:/var/lib/postgresql/data
            - ./ssh/:/tmp/.ssh/keys

    pg-1:
        image: postdock/postgres:latest-postgres11-repmgr40
        environment:
            NODE_ID: 2 # Integer number of node (not required if can be extracted from NODE_NAME var, e.g. node-45 => 1045)
            NODE_NAME: node2 # Node name
            CLUSTER_NODE_NETWORK_NAME: pg-1
            
            PARTNER_NODES: "pg-0,pg-1"
            REPLICATION_PRIMARY_HOST: pg-0 # That should be ignored on the same node
            
            NODE_PRIORITY: 100  # (default: 100)
            SSH_ENABLE: 1
            CLEAN_OVER_REWIND: 1
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "listen_addresses:'*';max_replication_slots:5;max_connections:4096"
            REPLICATION_PASSWORD: replication_password # default is replication_pass
            
        ports:
            - 5423:5432
        networks:
            cluster2:
        volumes:
            - /data/a/pg1:/var/lib/postgresql/data
            - ./ssh/:/tmp/.ssh/keys

    pgpool-2:
        image: postdock/pgpool:latest-pgpool37-postgres11
        environment:
            PCP_USER: pcp_user
            PCP_PASSWORD: pcp_pass
            WAIT_BACKEND_TIMEOUT: 60

            CHECK_USER: kalend
            CHECK_PASSWORD: 111222
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy
            SSH_ENABLE: 1
            DB_USERS: kalend:111222 # in format user:password[,user:password[...]]
            BACKENDS: "0:pg-0:5432:::ALLOW_TO_FAILOVER,1:pg-1::::" #,4:pgslaveDOES_NOT_EXIST::::
                      # in format num:host:port:weight:data_directory:flag[,...]
                      # defaults:
                      #   port: 5432
                      #   weight: 1
                      #   data_directory: /var/lib/postgresql/data
                      #   flag: ALLOW_TO_FAILOVER
            REQUIRE_MIN_BACKENDS: 1 # minimal number of backends to start pgpool (some might be unreachable)
            CONFIGS: "num_init_children:1024,max_pool:1"
                      # in format variable1:value1[,variable2:value2[,...]] if CONFIGS_DELIMITER_SYMBOL=, and CONFIGS_ASSIGNMENT_SYMBOL=:
                      # used for pgpool.conf file
        ports:
            - 5430:5432
            - 9898:9898 # PCP
        networks:
            cluster2:
        volumes:
            - ./ssh:/tmp/.ssh/keys
